PRIMARY_BLUE = "#3a7eb6"
PRIMARY_BLUE_DARK = "#1f5380"
PRIMARY_BLUE_HOVER = "#4a8ec6"
PRIMARY_BLUE_HOVER_DARK = "#2a6390"

SECONDARY_GRAY = "#4a4a4a"
SECONDARY_GRAY_DARK = "#2b2b2b"

BORDER_LIGHT = "#5a5a5a"
BORDER_DARK = "#3a3a3a"

LINE_COLOR = PRIMARY_BLUE
GRID_COLOR = "#3a3a3a"
START_POINT_COLOR = "#00cc66"
END_POINT_COLOR = "#ff5555"

MIN_CANVAS_SIZE = 10
MAX_CANVAS_SIZE = 5000
DEFAULT_CANVAS_WIDTH = 800
DEFAULT_CANVAS_HEIGHT = 600

MIN_SCALE = 0.1
MAX_SCALE = 10.0
ZOOM_FACTOR = 1.2

ALGORITHMS = {
    "DDA": "Алгоритм ЦДА",
    "Bresenham": "Алгоритм Брезенхема",
    "Wu": "Алгоритм Ву"
}